/*
Generated by LwipMibCompiler
*/

#ifndef SNMP_PULSE_H
#define SNMP_PULSE_H SNMP_PULSE_H

#include "lwip/apps/snmp_opts.h"
#if LWIP_SNMP

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include "lwip/apps/snmp_core.h"

extern const struct snmp_mib pulse;

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* LWIP_SNMP */
#endif /* SNMP_PULSE_H */
